생능 출판사 "으뜸 데이터 분석과 머신러닝"(개정판) 소스 코드 발췌 (저자 : 박동규, 강영민, 김병욱)

In [2]:
import numpy as np

a = np.array([1, 2, 3])
a.shape

(3,)

In [3]:
import numpy as np
a = np.array([[1,2,3,4],
              [2,3,4,5]])
# a[행, 열] 이렇게 간다.
a[0][1]# 0번째 행, 1번째 열

np.int64(2)

## Python Lists vs. NumPy

In [4]:
store_a = [20, 10, 30]  # 매장 A의 매출 : 파이썬 리스트로 표현
store_b = [70, 90, 70]  # 매장 B의 매출 : 파이썬 리스트로 표현

In [5]:
list_sum = store_a + store_b    # 파이썬 리스트의 더하기 연산
list_sum

[20, 10, 30, 70, 90, 70]

In [6]:
np_store_a = np.array(store_a)  # store_a 리스트를 넘파이 배열로 변환
np_store_b = np.array(store_b)  # store_b 리스트를 넘파이 배열로 변환

In [7]:
array_sum = np_store_a + np_store_b  # 넘파이 배열의 덧셈 결과를 확인하자
array_sum # element-wise 연산 지원

array([ 90, 100, 100])

## Key array properties

In [64]:
a = np.array([[2],
              [3],
              [4]]) # 넘파이 ndarray 객체의 생성
a = np.array([[1,2,3],[2,3,4]])

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size
#print(a.shape)

((2, 3), 2, dtype('int64'), 8, 6)

In [9]:
a = np.array([10, 20, 30])   # 넘파이 ndarray 객체 a 생성
b = np.array([1, 2, 3])      # 넘파이 ndarray 객체 b 생성
a + b

array([11, 22, 33])

In [10]:
a - b

array([ 9, 18, 27])

In [11]:
a * b

array([10, 40, 90])

In [12]:
a / b

array([10., 10., 10.])

### **Mini excercise 1**

In [68]:
# 직접 2차원 ndarray 객제를 하나 생성해서 shape, ndim, size를 출력해보자
a = np.array([[1,2,3],[2,3,4]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


#### NOTE : How to designate a datatype of an ndarray instance

In [67]:
a = np.array([1, 2, 3, 4], dtype = np.float32)

In [15]:
a = np.array([1, 2, 3, 4], dtype = 'int32')

## Broadcasting

In [16]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [17]:
a + 10

array([20, 30, 40])

In [18]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4]) # [[2, 3, 4], [2, 3, 4]] 로 리스트 롹장이 된다.
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [19]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

### **Mini excercise2**

In [20]:
# (2,3), (1,3) 형상의 배열을 생성하고 덧셈과 곱셈을 수행해보자
a = np.array([[1,2,3],[2,3,4]])
b = np.array([1,2,3])
a * b


array([[ 1,  4,  9],
       [ 2,  6, 12]])

## Creating Special Arrays

In [21]:
np.zeros((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full((2, 3), 100) # 2행 3열의 행렬 생성시 모든 값을 100으로

array([[100, 100, 100],
       [100, 100, 100]])

In [24]:
np.eye(3) # 3x3 크기의 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Generating Continuous Ranges

In [25]:
np.arange(0, 10) # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = np.arange(0, 10, 2) # 2씩 증가하는 수열을 생성


In [27]:
np.arange(0.0, 1.0, 0.2) # 0.2씩 증가하는 수열을 생성

array([0. , 0.2, 0.4, 0.6, 0.8])

In [28]:
np.linspace(0, 10, 5)
a = np.arange(0, 5, 0.5)
b = np.linspace(0, 5, 11)
print(a)
print(b)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [29]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [30]:
a = np.logspace(0, 5, 6).round(10) # 10^0에서 10^5까지 6개의 수를
a                                  # 로그 스케일 균일한 간격으로 생성한다.

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [31]:
np.log10(a) # a 배열에 로그를 취하면 0, 1, 2, 3, 4, 5가 생성됨

array([0., 1., 2., 3., 4., 5.])

### **Mini excercise 3**

In [32]:
#import matplotlib.pyplot as plt
x = np.linspace(0, 2*np.pi, 10)
# 0에서 pi까지의 범위에서 10개의 구간으로 나눈 각도를 입력으로 받아 sin 함수를 계산해서 출력해보자
# 단, pi값은 np.pi를, sin 함수는 np.sin() 함수를 사용한다.
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

## Array Dimensions and Insertion

In [33]:
# 1d 배열
a1 = np.array([2,3,5]) # shape(3,)
print(a1.shape)
# 2d 배열
a2 = np.array([[2,3,5]]) # shape(1, 3)
print(a2.shape)
# 2d 배열
a3 = np.array([[2], [3], [5]])
print(a3.shape)

(3,)
(1, 3)
(3, 1)


In [34]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2) # array, index, value, axis
np.insert([1,2,3], 1, 100)
a = np.insert(a, 1, 10000)
a

array([    1, 10000,     3,     4])

In [35]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis = 0) # 4는 자동으로 broadcasting 해서 insert 된다!

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [36]:
np.insert(b, 1, 4, axis = 1) # (3,1) 열벡터가 insert 된다.

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [37]:
c = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(c, axis=1)


array([[3, 2, 1],
       [6, 5, 4]])

In [38]:
np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

## Indexing, Slicing, Logical Indexing

In [72]:
a = np.array( [[1, 2, 3], [4, 5, 6],
               [7, 8, 9], [0, 1, 2]] )
print(a)
print(a[0][0])
print(a[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]
1
[7 8 9]


In [75]:
a[1:, 0:2]
#a[1:][0:2]
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
length0, length1 = a.shape
for i in range(length0):
    for j in range(length1):
        print(a[i][j], a[i, j])

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


In [42]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 2]])
a[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [83]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [87]:
a[ a % 2 == 0 ]



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### **Mini excercise 4**

In [96]:
# 1에서 100까지의 정수 중 3의 배수만을 원소로 갖는 1차원 배열을 생성하자
# 단, 1에서 100까지의 정수는 np.arange() 함수를 사용해서 생성한다.
# n = np.arange(3,101,3) 솔루션 1
n = np.arange(1,101)
n[n%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## Max, Min, Mean, Sorting

In [97]:
import numpy as np

a = np.array([10, 20, 30])
a.max(), a.min()           # a 배열원소 중 최대값, 최소값을 출력함

(np.int64(30), np.int64(10))

In [98]:
a.mean()

np.float64(20.0)

In [99]:
a.astype(np.float64)

array([10., 20., 30.])

In [100]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten() # 넘파이 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [101]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

In [102]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort() # 배열의 정렬(오름차순)
c[::-1] # 내림차순 정렬

array([99, 69, 55, 35, 24, 19])

In [52]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()         # 배열의 정렬, 디폴트 axis는 1
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [53]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)   # axis=0 방향 정렬
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

## Appending and Reshaping

In [103]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]]) # axis 가 없으면 1차원으로 펼쳐서 합친다.
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.append([a], b, axis = 0) # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
a = [1, 2, 3, 4, 5, 6, 7, 8]     # 1차원 리스트 a
b = np.reshape(a,(2,4)) # 2행4열 행렬 b 2*4 = a.size 여야 한다.
c = np.reshape(a,(4,2)) # 4행2열 행렬 c
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [107]:
a = np.arange(1,9)   # 1차원 배열 a
b = a.reshape(2,2,2) # 3차원 배열 b
b

[1 2 3 4 5 6 7 8]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [111]:
# b[0]은 3차원 배열 b의 첫 번째 차원에서 첫 번째 값을 선택
b[0][0][0]

np.int64(1)

In [116]:
# 5열로 구성된 2차원 배열로 변환
a=np.arange(10).reshape(-1,5)#첫번째 차원의 -1 은 자동계산 기능이다. x*5 = a.size
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
# 1차원 배열로 변환
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Mini excercise 4**

In [119]:
a = [1, 2, 3, 4, 5, 6, 7, 8] #를 4열로 변환하자. 단, 행의 수는 자동으로 계산되게 하자
a=np.array(a)
a.reshape(-1, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Random Numbers (Pseudo-Random)

In [120]:
def pseudo_rand(x):
    a = 1103515245
    b = 12345
    m = 2 ** 31
    new_x = (a * x + b) % m
    return new_x

seed = 100 # 초기값을 임의로 설정하자 동일한 seed 에서는 동일한 값이 나온다.

x = pseudo_rand(seed) # seed를 입력으로 하여 새로운 x를 만들자
print(x)
x = pseudo_rand(x) # x_n을 입력으로 하여 새로운 x_(n+1)을 만들자
print(x)

829870797
1533044610


In [94]:
import numpy as np
# 5개의 균등분포 난수를 생성
np.random.rand(5)

array([0.54419824, 0.14425136, 0.48322111, 0.90930956, 0.34664423])

In [123]:
np.random.randint(150, 191, size=10) # 150 이상 191 미만의 랜덤 정수 10개 생성

array([166, 190, 190, 151, 161, 163, 184, 174, 177, 152], dtype=int32)

## NumPy’s Random Module

In [124]:
rnd = np.random.randn(5) * 10 + 165 # 평균값이 165,표준편차가 10인 값 생성
rnd

array([171.08369822, 167.47247179, 165.49954889, 153.2819475 ,
       171.95202871])

In [97]:
rnd.round(2)       # 소수점 아래 둘째 자리까지 값으로 변환

array([164.68, 162.57, 160.95, 183.17, 167.78])

In [98]:
rnd.astype(int)    # 정수형 자료형으로 변환

array([164, 162, 160, 183, 167])

In [104]:
np.random.seed(42) # 씨드 값이 특정될 경우 매번 동일한 난수의 열이 생성됨

In [107]:
np.random.seed(42) # 씨드 값이 특정될 경우 매번 동일한 난수의 열이 생성됨
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2) # 평균, 표준편차, shape, round(2) 로 소수점 2번째 자리까지 (커스터 마이즈 정규분포)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

## Measuring Vectorized Performance

In [108]:
import numpy as np
import time        # 수행시간 측정을 위하여 time 모듈을 가져온다

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [109]:
start = time.time()
for i in range(len(arr_a)):    # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간: ', end - start)

소요시간:  0.0011448860168457031


In [110]:
start = time.time()
result = arr_a * arr_b # 벡터화 연산 *(vectorization) 이 훠어어얼씬 빠름
end = time.time()
print('소요시간: ', end - start)
print('소요시간: {:12.10f}'.format(end - start))

소요시간:  0.00021266937255859375
소요시간: 0.0002126694


In [111]:
n_elem = 100000 # 원소의 개수
arr_a = np.random.rand(n_elem)
arr_b = np.random.rand(n_elem)
result = np.zeros(n_elem)

In [112]:
start = time.time()
for i in range(n_elem): # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]

end = time.time()
print('원소별 접근 방식 소요시간: ', end - start)

start = time.time()
result = arr_a * arr_b
end = time.time()
print('벡터화 연산 수행 소요시간: ', end - start)

원소별 접근 방식 소요시간:  0.0608367919921875
벡터화 연산 수행 소요시간:  0.0005102157592773438


## Reduction Operations

In [114]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
               ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0, 1)) # axis = (0, 1)은 생략 가능

[ 5 10 15 20 25]
[15 15 15 15 15]


np.int64(75)

In [115]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

In [116]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500088.6615472703 
계산 시간:  0.28455400466918945


In [117]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_reduction,"\n계산 시간: ",end-start)

1000 x 1000 배열의 원소 합 500088.66154726536 
계산 시간:  0.0028405189514160156


## Linear Algebra (Solving Equations)

In [118]:
# solving for as = b
a = np.array([[1,2], [1,-3]])
b = np.array([6,1])
s = np.linalg.solve(a,b)
print(s)

[4. 1.]


In [ ]:
a = np.array([[2,1], [4,5]])
det_a = np.linalg.det(a)
b = np.array([[1,2], [3,-6]])
det_b = np.linalg.det(b)
print(det_a, det_b)

## Concatenate, vstack, hstack


In [126]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [127]:
b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
c = np.arange(8).reshape(2,4)
c   # (2, 4) 형상의 다차원 배열로 0에서 7까지의 원소를 가짐

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [129]:
d = list(range(4))
d   # d는 1차원 리스트로 0에서 3까지의 원소를 가짐

[0, 1, 2, 3]

In [130]:
np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
np.vstack((a, b)) # a 배열과 b 배열을 수직 방향으로 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.vstack((a, d)) # a 배열과 d 리스트의 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [133]:
np.vstack((a, b, d)) # 다차원 배열 3개를 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [134]:
np.hstack((a, c))   # 다차원 배열 a, c를 수평으로 결합

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [135]:
# a 배열은 형상이 (2, 4), b 배열은 (3, 4)로 수평 결합이 안됨
np.hstack((a, b)) # a 배열과 b 배열의 hstack 결합-오류

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3