생능 출판사 "으뜸 데이터 분석과 머신러닝"(개정판) 소스 코드 발췌 (저자 : 박동규, 강영민, 김병욱)

In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
import numpy as np
a = np.array([[1,2,3,4],
              [2,3,4,5]])

## Python Lists vs. NumPy

In [3]:
store_a = [20, 10, 30]  # 매장 A의 매출 : 파이썬 리스트로 표현
store_b = [70, 90, 70]  # 매장 B의 매출 : 파이썬 리스트로 표현

In [4]:
list_sum = store_a + store_b    # 파이썬 리스트의 더하기 연산
list_sum

[20, 10, 30, 70, 90, 70]

In [5]:
np_store_a = np.array(store_a)  # store_a 리스트를 넘파이 배열로 변환
np_store_b = np.array(store_b)  # store_b 리스트를 넘파이 배열로 변환

In [6]:
array_sum = np_store_a + np_store_b  # 넘파이 배열의 덧셈 결과를 확인하자
array_sum

array([ 90, 100, 100])

## Key array properties

In [9]:
a = np.array([[2],
              [3],
              [4]]) # 넘파이 ndarray 객체의 생성

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3, 1), 2, dtype('int64'), 8, 3)

In [10]:
a = np.array([10, 20, 30])   # 넘파이 ndarray 객체 a 생성
b = np.array([1, 2, 3])      # 넘파이 ndarray 객체 b 생성
a + b

array([11, 22, 33])

In [11]:
a - b

array([ 9, 18, 27])

In [12]:
a * b

array([10, 40, 90])

In [13]:
a / b

array([10., 10., 10.])

### **Mini excercise 1**

In [ ]:
# 직접 2차원 ndarray 객제를 하나 생성해서 shape, ndim, size를 출력해보자


((3, 2), 2, 6)

#### NOTE : How to designate a datatype of an ndarray instance

In [ ]:
a = np.array([1, 2, 3, 4], dtype = np.float32)

In [ ]:
a = np.array([1, 2, 3, 4], dtype = 'int32')

## Broadcasting

In [15]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [16]:
a + 10

array([20, 30, 40])

In [17]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [18]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

### **Mini excercise2**

In [ ]:
# (2,3), (1,3) 형상의 배열을 생성하고 덧셈과 곱셈을 수행해보자


array([[ 3,  8, 15],
       [12, 20, 30]])

## Creating Special Arrays

In [21]:
np.zeros((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full((2, 3), 100) # 2행 3열의 행렬 생성시 모든 값을 100으로

array([[100, 100, 100],
       [100, 100, 100]])

In [24]:
np.eye(3) # 3x3 크기의 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Generating Continuous Ranges

In [25]:
np.arange(0, 10) # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 10, 2) # 2씩 증가하는 수열을 생성

array([0, 2, 4, 6, 8])

In [27]:
np.arange(0.0, 1.0, 0.2) # 0.2씩 증가하는 수열을 생성

array([0. , 0.2, 0.4, 0.6, 0.8])

In [28]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [30]:
a = np.logspace(0, 5, 6).round(10) # 10^0에서 10^5까지 6개의 수를
a                                  # 로그 스케일 균일한 간격으로 생성한다.

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [31]:
np.log10(a) # a 배열에 로그를 취하면 0, 1, 2, 3, 4, 5가 생성됨

array([0., 1., 2., 3., 4., 5.])

### **Mini excercise 3**

In [ ]:
# 0에서 pi까지의 범위에서 10개의 구간으로 나눈 각도를 입력으로 받아 sin 함수를 계산해서 출력해보자
# 단, pi값은 np.pi를, sin 함수는 np.sin() 함수를 사용한다.


array([0.00000000e+00, 3.17279335e-02, 6.34239197e-02, 9.50560433e-02,
       1.26592454e-01, 1.58001396e-01, 1.89251244e-01, 2.20310533e-01,
       2.51147987e-01, 2.81732557e-01, 3.12033446e-01, 3.42020143e-01,
       3.71662456e-01, 4.00930535e-01, 4.29794912e-01, 4.58226522e-01,
       4.86196736e-01, 5.13677392e-01, 5.40640817e-01, 5.67059864e-01,
       5.92907929e-01, 6.18158986e-01, 6.42787610e-01, 6.66769001e-01,
       6.90079011e-01, 7.12694171e-01, 7.34591709e-01, 7.55749574e-01,
       7.76146464e-01, 7.95761841e-01, 8.14575952e-01, 8.32569855e-01,
       8.49725430e-01, 8.66025404e-01, 8.81453363e-01, 8.95993774e-01,
       9.09631995e-01, 9.22354294e-01, 9.34147860e-01, 9.45000819e-01,
       9.54902241e-01, 9.63842159e-01, 9.71811568e-01, 9.78802446e-01,
       9.84807753e-01, 9.89821442e-01, 9.93838464e-01, 9.96854776e-01,
       9.98867339e-01, 9.99874128e-01, 9.99874128e-01, 9.98867339e-01,
       9.96854776e-01, 9.93838464e-01, 9.89821442e-01, 9.84807753e-01,
      

## Array Dimensions and Insertion

In [38]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [39]:
b = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(b, 1, 4, axis = 0) # 4는 자동으로 broadcasting

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [40]:
np.insert(b, 1, 4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [41]:
c = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(c, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [42]:
np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

## Indexing, Slicing, Logical Indexing

In [44]:
a = np.array( [[1, 2, 3], [4, 5, 6],
               [7, 8, 9], [0, 1, 2]] )

print(a[0][0])
print(a[2])

1
8


In [45]:
a[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
length0, length1 = a.shape
for i in range(length0):
    for j in range(length1):
        print(a[i][j], a[i, j])

In [46]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 2]])
a[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [47]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [48]:
a[ a % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### **Mini excercise 4**

In [ ]:
# 1에서 100까지의 정수 중 3의 배수만을 원소로 갖는 1차원 배열을 생성하자
# 단, 1에서 100까지의 정수는 np.arange() 함수를 사용해서 생성한다.


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## Max, Min, Mean, Sorting

In [51]:
import numpy as np

a = np.array([10, 20, 30])
a.max(), a.min()           # a 배열원소 중 최대값, 최소값을 출력함

(30, 10)

In [52]:
a.mean()

20.0

In [53]:
a.astype(np.float64)

array([10., 20., 30.])

In [54]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten() # 넘파이 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [55]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

In [56]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort() # 배열의 정렬(오름차순)
c[::-1] # 내림차순 정렬

array([99, 69, 55, 35, 24, 19])

In [57]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()         # 배열의 정렬, 디폴트 axis는 1
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [58]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)   # axis=0 방향 정렬
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

## Appending and Reshaping

In [59]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.append([a], b, axis = 0) # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a = [1, 2, 3, 4, 5, 6, 7, 8]     # 1차원 리스트 a
b = np.reshape(a,(2,4)) # 2행4열 행렬 b
c = np.reshape(a,(4,2)) # 4행2열 행렬 c
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
c

In [62]:
a = np.arange(1,9)   # 1차원 배열 a
b = a.reshape(2,2,2) # 3차원 배열 b
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
# b[0]은 3차원 배열 b의 첫 번째 차원에서 첫 번째 값을 선택
b[0]

array([[1, 2],
       [3, 4]])

In [64]:
# 5열로 구성된 2차원 배열로 변환
a=np.arange(10).reshape(-1,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# 1차원 배열로 변환
a.reshape(-1)

### **Mini excercise 4**

In [ ]:
# a = [1, 2, 3, 4, 5, 6, 7, 8] 를 4열로 변환하자. 단, 행의 수는 자동으로 계산되게 하자


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Random Numbers (Pseudo-Random)

In [67]:
def pseudo_rand(x):
    a = 1103515245
    b = 12345
    m = 2 ** 31
    new_x = (a * x + b) % m
    return new_x

seed = 100 # 초기값을 임의로 설정하자

x = pseudo_rand(seed) # seed를 입력으로 하여 새로운 x를 만들자
print(x)
x = pseudo_rand(x) # x_n을 입력으로 하여 새로운 x_(n+1)을 만들자
print(x)

829870797
1533044610


In [68]:
import numpy as np
# 5개의 균등분포 난수를 생성
np.random.rand(5)

array([0.73150432, 0.81343085, 0.15368786, 0.59043813, 0.19644617])

In [69]:
np.random.randint(150, 191, size=10)

array([190, 168, 166, 177, 184, 184, 159, 155, 190, 156])

## NumPy’s Random Module

In [87]:
rnd = np.random.randn(5) * 10 + 165 # 평균값이 165,표준편차가 10인 값 생성
rnd

array([174.99564623, 163.80949735, 174.08204996, 179.52873936,
       172.71992283])

In [90]:
rnd.round(2)       # 소수점 아래 둘째 자리까지 값으로 변환

array([175.  , 163.81, 174.08, 179.53, 172.72])

In [ ]:
rnd.astype(int)    # 정수형 자료형으로 변환

In [112]:
np.random.seed(42) # 씨드 값이 특정될 경우 매번 동일한 난수의 열이 생성됨

In [124]:
np.random.seed(42) # 씨드 값이 특정될 경우 매번 동일한 난수의 열이 생성됨
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

## Measuring Vectorized Performance

In [ ]:
import numpy as np
import time        # 수행시간 측정을 위하여 time 모듈을 가져온다

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [ ]:
start = time.time()
for i in range(len(arr_a)):    # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간: ', end - start)

In [ ]:
start = time.time()
result = arr_a * arr_b # 벡터화 연산 *
end = time.time()
print('소요시간: ', end - start)
print('소요시간: {:12.10f}'.format(end - start))

In [ ]:
n_elem = 100000 # 원소의 개수
arr_a = np.random.rand(n_elem)
arr_b = np.random.rand(n_elem)
result = np.zeros(n_elem)

In [ ]:
start = time.time()
for i in range(n_elem): # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]

end = time.time()
print('원소별 접근 방식 소요시간: ', end - start)

start = time.time()
result = arr_a * arr_b
end = time.time()
print('벡터화 연산 수행 소요시간: ', end - start)

## Reduction Operations

In [ ]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
               ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0, 1)) # axis = (0, 1)은 생략 가능

In [ ]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

In [ ]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

In [ ]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_reduction,"\n계산 시간: ",end-start)

## Linear Algebra (Solving Equations)

In [ ]:
# solving for as = b
a = np.array([[1,2], [1,-3]])
b = np.array([6,1])
s = np.linalg.solve(a,b)
print(s)

In [ ]:
a = np.array([[2,1], [4,5]])
det_a = np.linalg.det(a)
b = np.array([[1,2], [3,-6]])
det_b = np.linalg.det(b)
print(det_a, det_b)

## Concatenate, vstack, hstack


In [ ]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

In [ ]:
b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

In [ ]:
c = np.arange(8).reshape(2,4)
c   # (2, 4) 형상의 다차원 배열로 0에서 7까지의 원소를 가짐

In [ ]:
d = list(range(4))
d   # d는 1차원 리스트로 0에서 3까지의 원소를 가짐

In [ ]:
np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다

In [ ]:
np.vstack((a, b)) # a 배열과 b 배열을 수직 방향으로 결합

In [ ]:
np.vstack((a, d)) # a 배열과 d 리스트의 결합

In [ ]:
np.vstack((a, b, d)) # 다차원 배열 3개를 결합

In [ ]:
np.hstack((a, c))   # 다차원 배열 a, c를 수평으로 결합

In [ ]:
# a 배열은 형상이 (2, 4), b 배열은 (3, 4)로 수평 결합이 안됨
np.hstack((a, b)) # a 배열과 b 배열의 hstack 결합-오류